### ISSUE TITLE
The web page shows empty (white) web page (just the menu icon on the top left)

### ISSUE THREAD

**Issue by dforouhari** [KhaledSharif/cesium-satellites#2]
Hello Mr.Sharif. Hope you can be of help.
1. Setup & config info
OS: Ubuntu 16.04
Browser: Chrome 68.0.3440.106 (Official Build) (64-bit)
Docker: version 18.09.3, build 774a1f4

2. After downloading & unzip the file,
$ docker build ... command finished without any errors
$ docker image,  shows the entry for the image,
$ docker run -d -p 8080:80 cesium:satellites
fafe1f86c70aef7636da1a88bc5a0c88668cca87ef2eb9e25b9116e6ab11dca0
$ docker container list
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                  NAMES
fafe1f86c70a        cesium:satellites   "/bin/sh -c 'wget -P…"   52 seconds ago      Up 49 seconds       0.0.0.0:8080->80/tcp   gracious_ramanujan

Opening the Chrome browser with URL localhost:8080 displayes a web page
- in white color, split into two horizontal frames; the top frame being a narrow one with a menu icon (three short black horizontal) at the left. The bottom bigger frame  empty. 
- clicking on the menu, splits the white page into two vertical frames; the left frame has the word 'Satellites' on the top, with nothing else displayed.

3. Below is the 'docker logs' output:
$ docker logs fafe1f86c70a
--2019-03-03 04:44:17--  http://celestrak.com/NORAD/elements/stations.txt
Resolving celestrak.com (celestrak.com)... 75.151.179.89
Connecting to celestrak.com (celestrak.com)|75.151.179.89|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9072 (8.9K) [text/plain]
Saving to: '/usr/share/nginx/html/stations.txt'

     0K ........                                              100% 3.46M=0.002s

2019-03-03 04:44:18 (3.46 MB/s) - '/usr/share/nginx/html/stations.txt' saved [9072/9072]

172.17.0.1 - - [03/Mar/2019:04:44:28 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "-"
172.17.0.1 - - [03/Mar/2019:04:44:28 +0000] "GET /bundle.js HTTP/1.1" 304 0 "http://localhost:8080/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "-"
2019/03/03 04:44:29 [error] 8#8: *1 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 172.17.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost:8080", referrer: "http://localhost:8080/"
172.17.0.1 - - [03/Mar/2019:04:44:29 +0000] "GET /favicon.ico HTTP/1.1" 404 571 "http://localhost:8080/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "-"

I would appreciate hearing back from you.

Best regards,
dforouhari

**Comment by KhaledSharif** [comment]
@dforouhari thanks for filing the issue. I've just merged in a pull request from @pncbose that should fix this. Please let me know if the error persists. Thanks!
